# Generated by Django 4.0.1 on 2022-11-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_views_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='people',
        ),
    ]
